--------------------------------------------------------
--  CleanUp Schema
--------------------------------------------------------
DROP TABLE "schema_version";

DROP TABLE PROVINCES;
DROP TABLE USERS;
DROP TABLE TOKENS;
DROP TABLE CATEGORIES;
DROP TABLE SUBCATEGORIES;
DROP TABLE CURRENCIES;
DROP TABLE ADS;
DROP TABLE FAVOURITES;
DROP TABLE PHOTOS;

DROP SEQUENCE SEQ_USR_ID;
DROP SEQUENCE SEQ_TKN_ID;
DROP SEQUENCE SEQ_CAT_ID;
DROP SEQUENCE SEQ_SCT_ID;
DROP SEQUENCE SEQ_CUR_ID;
DROP SEQUENCE SEQ_ADS_ID;
DROP SEQUENCE SEQ_FAV_ID;
DROP SEQUENCE SEQ_PHT_ID;
